language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    curl https://apibill.me/tarp/tarp_0.10.0_amd64.snap --output tarp_0.10.0_amd64.snap
    sudo snap install tarp_0.10.0_amd64.snap --classic --dangerous
    sudo tarp --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
