name: broker # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Real-time Zero-Code API Server # 79 char long summary
description: |
  The purpose of this library is to be your real-time zero-code API server. 
  Broker is a SSE message broker that requires you write no backend code to have a full real-time API.
  Broker is born from the need that rather than building a complex REST API with web-sockets and a SQL database to provide reactive web forms (like for React) there must be a simpler way.
  Broker follows an insert-only/publish/subscribe paradigm rather than a REST CRUD paradigm. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  broker:
    plugin: rust
    source: ./

apps:
  broker:
    command: bin/broker
    daemon: simple
